# permissions for end users to view rollouts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rollout-viewer-role
rules:
- apiGroups:
  - apps.kruise.io
  resources:
  - rollouts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.kruise.io
  resources:
  - rollouts/status
  verbs:
  - get
