apiVersion: apps.kruise.io/v1alpha1
kind: PodMarker
metadata:
  name: marker
spec:
  strategy:
    confilctPolicy: Ignore
  matchRequirements:
    podSelector:
      matchLabels:
        app: nginx
  matchPreferences:
    - podSelector:
        matchLabels:
          pod.state: working_online
    - podReady: true
  markItems:
    labels:
      upgradeStrategy: inPlace
    annotations:
      markUpgradeStrategyUsingPodMarker: marker